### PR TITLE
Update dependencies, particularly regex

### PR DESCRIPTION
**Pull request by Freaky**
A simple mechanical update, validated with `cargo test`.

### CODE REVIEW

**Comment by klausi** [comment]
This shows now up as dependabot alert and `cargo audit` security issue because the old regex crate is considered insecure.

@QuietMisdreavus hi, do you have time to merge this and make a new egg-mode-text release?

**Review by QuietMisdreavus — APPROVED** [review]
Thanks!

**Comment by QuietMisdreavus** [comment]
I've published egg-mode-text 1.15.0 with this update.

**Comment by klausi** [comment]
Very much appreciated, thank you!

**Pull request merged**
